FROM base-srt:v2
ENV INPUT_PORT=4200
ENV REPORT_FREQUENCY=1000ms
RUN echo "'Listening in port $INPUT_PORT'"
RUN echo "'Report frequency set to $REPORT_FREQUENCY milliseconds'"
CMD ./bin/srt-xtransmit receive "srt://:$INPUT_PORT?transtype=live&rcvbuf=1000000000&sndbuf=1000000000" --msgsize 1316 --statsfile /logs/stats-rcv.csv --statsfreq 100ms
