FROM base-srt:v1
CMD ffmpeg -f lavfi -re -i smptebars=duration=300:size=1280x720:rate=30 -f lavfi -re -i sine=frequency=1000:duration=60:sample_rate=44100 -pix_fmt yuv420p -c:v libx264 -b:v 1000k -g 30 -keyint_min 120 -profile:v baseline -preset veryfast -f mpegts "udp://127.0.0.1:1234?pkt_size=1316"
-pix_fmt yuv420p \
-c:v libx264 \
-b:v 1000k \
-g 30 \
-keyint_min 120 \
-profile:v baseline \
-preset fast \
-f mpegts \
"udp://127.0.0.1:1234?pkt_size=1316"
CMD ./srt/build/srt-live-transmit udp://:1234 srt://104.198.79.60:4201 -v