FROM deep-srt-base:v1
ENV MEDIUM=srt
ENV RECEIVER_ADDRESS=127.0.0.1
ENV RECEIVER_PORT=1235
ENV REPORT_FREQUENCY=1000
ENV LATENCY=100
RUN echo "'Transmitting to $RECEIVER_ADDRESS in port $RECEIVER_PORT'"
RUN echo "'Report frequency set to $REPORT_FREQUENCY milliseconds'"
COPY entrypoint.sh /
CMD ["/entrypoint.sh"]
