FROM base-srt:v1
CMD ffmpeg -f lavfi \
-re -i smptebars=duration=300:size=1280x720:rate=30 \
-f lavfi \
-re -i sine=frequency=1000:duration=60:sample_rate=44100 \
-pix_fmt yuv420p \
-c:v libx264 \
-b:v 1000k \
-g 30 \
-keyint_min 120 \
-profile:v baseline \
-preset fast \
-f mpegts \
"udp://127.0.0.1:1234?pkt_size=1316"
ENV MEDIUM=srt
ENV RECEIVER_ADDRESS=127.0.0.1
ENV RECEIVER_PORT=1235
ENV REPORT_FREQUENCY=1000
CMD echo "'Transmitting to $RECEIVER_ADDRESS in port $RECEIVER_PORT'"
CMD echo "'Report frequency set to $REPORT_FREQUENCY milliseconds'"
CMD ./srt/build/srt-live-transmit udp://localhost:1234 $MEDIUM://$RECEIVER_ADDRESS:$RECEIVER_PORT -v -stats-report-frequency $REPORT_FREQUENCY -statsout -pf csv