FROM ubuntu:latest

RUN apt-get update --fix-missing

# Get git
RUN apt-get install git -y 
# Get cmake and compiler tools
RUN apt-get install pkg-config cmake libssl-dev build-essential -y

# Get srt xtransmit
RUN git clone https://github.com/maxsharabayko/srt-xtransmit.git srt-xtransmit
WORKDIR "srt-xtransmit"
RUN git submodule init
RUN git submodule update
RUN mkdir _build && cd _build
RUN cmake .
RUN cmake --build ./

# Get tshark
RUN apt-get update
RUN apt-get install -y net-tools
RUN DEBIAN_FRONTEND=noninteractive apt install -y tshark